### ISSUE TITLE
[BUG] vela app:ls crash

### ISSUE THREAD

**Issue by erdun** [cloud-native-application/RudrX#112]
```
./bin/vela app:ls

panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/cloud-native-application/rudrx/pkg/cmd/util.RetrieveApplicationsByName(0x29a7040, 0xc000044140, 0x29bee00, 0xc000931020, 0x0, 0x0, 0xc0004837a8, 0x7, 0x1022615, 0xc000931020, ...)
	/Users/dingxiaohua/go/src/github.com/cloud-native-application/rudrx/pkg/cmd/util/helpers.go:146 +0x931
github.com/cloud-native-application/rudrx/pkg/cmd.printApplicationList(0x29a7040, 0xc000044140, 0x29bee00, 0xc000931020, 0x0, 0x0, 0xc0004837a8, 0x7)
	/Users/dingxiaohua/go/src/github.com/cloud-native-application/rudrx/pkg/cmd/ls.go:45 +0x9e
github.com/cloud-native-application/rudrx/pkg/cmd.NewAppsCommand.func1(0xc0001b5600, 0x377c760, 0x0, 0x0, 0x0, 0x0)
	/Users/dingxiaohua/go/src/github.com/cloud-native-application/rudrx/pkg/cmd/ls.go:32 +0xf9
github.com/spf13/cobra.(*Command).execute(0xc0001b5600, 0x377c760, 0x0, 0x0, 0xc0001b5600, 0x377c760)
	/Users/dingxiaohua/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc00016d340, 0x16293cd6d60e6ce8, 0x3742980, 0x1007a5f)
	/Users/dingxiaohua/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/dingxiaohua/go/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
main.main()
	/Users/dingxiaohua/go/src/github.com/cloud-native-application/rudrx/cmd/vela/main.go:62 +0xe6
```

**Comment by zzxwill** [comment]
@erdun Thanks for filing the issue. I didn't reproduce it. Could you please help provide more information?
