### ISSUE TITLE
[BUG] containerized:run issue

### ISSUE THREAD

**Issue by zzxwill** [cloud-native-application/RudrX#91]
```
Application
/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/e2e/application/application_test.go:17
  run
  /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/e2e/commonContext.go:75
    should print successful creation information [It]
    /Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/e2e/commonContext.go:76

    Expected
        <string>: panic: assignment to entry in nil map

        goroutine 1 [running]:
        github.com/cloud-native-application/rudrx/pkg/cmd.(*runOptions).Complete(0xc00047b400, 0xc0000ceb00, 0xc00071e870, 0x1, 0x5, 0x281f860, 0xc0000d80a8, 0xc000a11cf0, 0x0)
        	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/pkg/cmd/workload_run.go:114 +0x30a
        github.com/cloud-native-application/rudrx/pkg/cmd.AddWorkloadPlugins.func1(0xc0000ceb00, 0xc00071e870, 0x1, 0x5, 0x0, 0x0)
        	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/pkg/cmd/workload_run.go:57 +0x73
        github.com/spf13/cobra.(*Command).execute(0xc0000ceb00, 0xc00071e820, 0x5, 0x5, 0xc0000ceb00, 0xc00071e820)
        	/Users/zhouzhengxi/Programming/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:842 +0x460
        github.com/spf13/cobra.(*Command).ExecuteC(0xc0000cf340, 0x1628500206856920, 0x34d53c0, 0xc0001531f0)
        	/Users/zhouzhengxi/Programming/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:950 +0x349
        github.com/spf13/cobra.(*Command).Execute(...)
        	/Users/zhouzhengxi/Programming/golang/pkg/mod/github.com/spf13/cobra@v1.0.0/command.go:887
        main.main()
        	/Users/zhouzhengxi/Programming/golang/src/github.com/zzxwill/RudrX/cmd/rudrx/main.go:52 +0xce

    to contain substring
        <string>: SUCCEED
```
 Need to check line https://github.com/cloud-native-application/RudrX/blob/master/pkg/cmd/workload_run.go#L114

**Comment by wonderflow** [comment]
fixed by #92
